version: '3' 

services:

  leetforce-redis:
    image: redis:latest
    ports:
      - "6379:6379"

  leetforce-postgres:
    image: postgres
    environment: 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}  
      POSTGRES_USER: postgres                    # Optional, default user
      POSTGRES_DB: postgres  
    ports:
      - "5432:5432"
